### ISSUE TITLE
[BUG] 双层数据，选中数据展示栏无法清空，并自动添加数据

### ISSUE THREAD

**Issue by systemime** [ringocx/layui_cascader#3]
将样例中数据第二层children删除，数据如下
```json
[
    {
        "id":1000,
        "province_city":"北京",
        "fid":"0",
        "children":[
            {
                "id":1368,
                "province_city":"北京市",
                "fid":"1000",
                "children":[

                ]
            }
        ]
    },
    {
        "id":1001,
        "province_city":"上海",
        "fid":"0",
        "children":[
            {
                "id":1369,
                "province_city":"上海市",
                "fid":"1001",
                "children":[

                ]
            }
        ]
    }
]
```

前端界面自动选中第一行数据且无法删除，点击叉号会再次添加一遍，无法删除
![Kapture 2021-01-18 at 11 55 54](https://user-images.githubusercontent.com/30690006/104870816-60d41900-5984-11eb-841e-fe1897b4352a.gif)

**Comment by ringocx** [comment]
> 将样例中数据第二层children删除，数据如下
> 
> ```json
> [
>     {
>         "id":1000,
>         "province_city":"北京",
>         "fid":"0",
>         "children":[
>             {
>                 "id":1368,
>                 "province_city":"北京市",
>                 "fid":"1000",
>                 "children":[
> 
>                 ]
>             }
>         ]
>     },
>     {
>         "id":1001,
>         "province_city":"上海",
>         "fid":"0",
>         "children":[
>             {
>                 "id":1369,
>                 "province_city":"上海市",
>                 "fid":"1001",
>                 "children":[
> 
>                 ]
>             }
>         ]
>     }
> ]
> ```
> 
> 前端界面自动选中第一行数据且无法删除，点击叉号会再次添加一遍，无法删除
> ![Kapture 2021-01-18 at 11 55 54](https://user-images.githubusercontent.com/30690006/104870816-60d41900-5984-11eb-841e-fe1897b4352a.gif)

这个是数据有误，并不属于BUG

**Comment by systemime** [comment]
收到，感谢提醒
